name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDF
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    steps:
      - uses: actions/checkout@v4
      - name: Build the thesis
        run: latexmk thesis
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: |
            thesis.pdf
