name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDF
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the thesis
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: |
            thesis.pdf
